name: admin_page
description: "FefuFit admin console"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-16.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  scrollable_table_view: ^2.0.2
  flutter_svg: ^2.0.7
  slang: ^3.22.0
  slang_flutter: ^3.18.0
  # theme_tailor: ^2.0.0
  # theme_tailor_annotation: ^2.0.0
  go_router: ^10.0.0

  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  get_it: ^7.6.0

  chopper: ^7.0.5
  chopper_generator: ^7.0.2

  source_gen: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  
  email_validator: ^2.1.17
  flutter_native_splash: ^2.3.2
  logger: ^2.0.2
  get_storage: ^2.1.1

  # vibration: ^1.7.5
  # vibration_web: ^1.6.5
  
  ai_barcode_scanner: ^0.0.7


  flutter_localizations:
    sdk: flutter
  file_picker: ^5.5.0
  url_launcher: ^6.1.14
  ota_update: ^6.0.0

  fefufit_uikit:
    path: ../fefufit_uikit/
  
  balanced_text: ^0.0.3
  json_annotation: ^4.8.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

  json_serializable: ^6.7.1

 
 


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/

  fonts:
  # название семейства шрифтов
  - family: Roboto
    fonts:
      # для каждого файла шрифта мы прописываем 
      # соответствующие параметры
      - asset: assets/fonts/Roboto-Light.ttf
        style: normal
        weight: 300
      - asset: assets/fonts/Roboto-Regular.ttf
        style: normal
      - asset: assets/fonts/Roboto-Bold.ttf
        style: normal 
        weight: 700
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/img/logo_dark.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/logo_dark.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  

flutter_app_name:
  name: "FefuFit Admin"