name: admin_page
description: "FefuFit admin console"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-16.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  scrollable_table_view: ^2.0.2
  flutter_svg: ^2.0.7
  slang: ^3.22.0
  slang_flutter: ^3.18.0
  theme_tailor: ^2.0.0
  theme_tailor_annotation: ^2.0.0
  go_router: ^10.0.0

  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  get_it: ^7.6.0

  chopper: ^7.0.5
  chopper_generator: ^7.0.2

  source_gen: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  email_validator: ^2.1.17
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
  # название семейства шрифтов
  - family: Roboto
    fonts:
      # для каждого файла шрифта мы прописываем 
      # соответствующие параметры
      - asset: assets/fonts/Roboto-Light.ttf
        style: normal
        weight: 300
      - asset: assets/fonts/Roboto-Regular.ttf
        style: normal
      - asset: assets/fonts/Roboto-Bold.ttf
        style: normal 
        weight: 700