name: Build release

on:
  workflow_dispatch:
  
jobs:
  build_release:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          cache: true
          
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/fefufit_admin.apk

      - name: 📂Upload release
        uses: actions/upload-artifact@v3
        with:
            name: app-release
            path: build/app/outputs/flutter-apk/fefufit_admin.apk